title: Jesslene Lee # your name (or website title) here
logo:  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Department of Political Science
  University of Toronto
  <br><br>
  <a href="https://jesslenelee.github.io/research">Research</a> 
  <a href="https://jesslenelee.github.io/teaching">Research</a> 
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
